packages:
  - 'plugins/**'

patchedDependencies:
  body-parser@2: lib/modules/body-parser.patch
  compression: lib/modules/compression.patch
  log4js: lib/modules/log4js.patch
  streamroller: lib/modules/streamroller.patch

strictDepBuilds: false
allowBuilds:
  better-sqlite3: true
  log4js: true
  playwright: true
  sharp: true
onlyBuiltDependencies:
  - better-sqlite3
  - log4js
  - playwright
  - sharp
